In [5]:
import scipy
import numpy as np
x = np.array([[[1.0,2.0,3.0,4.0,5.0]]*3]*2)
k = np.array([0.0,0,1.0,0,0])

print("x", x)

res2 = scipy.ndimage.convolve1d(x, k, axis=-1, mode='constant', cval=0.0) #convolution using scipy straight forward

print("res", res2)

x [[[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]

 [[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]]
res [[[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]

 [[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]]


In [34]:
import torch
import torch.nn as nn
#convolution using pytorch

x = torch.tensor([[[1.0,2,3,4,5]]*3]*2) #batch of 2 2d tensor
k = torch.tensor([[0,0,2.0,0,0]]*3, dtype=torch.float32) #2d kernel

print("x\n", x)
print("filter\n", k)

res = nn.functional.conv1d(x, k[:, None, :], groups=3, padding="same") #allowing theta dependance in filter

print(res)

x
 tensor([[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]]])
filter
 tensor([[0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.]])
tensor([[[ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.]],

        [[ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.]]])


In [37]:
x = torch.tensor([
    [
        [1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5]
    ],
    [
        [1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5]
    ]

], dtype=torch.float32)
print("x\n",x)
print(x.shape)
# print(x[None].shape)
k = torch.tensor([0,0,2,0,0], dtype=torch.float32) #1d kernel

res = nn.functional.conv2d(x[:, None], k[None, None, None], padding="same") # no theta depandance in filter
#kernel and input need to be batch_size x channels x h x width, we have only one channel!
print("Result", res)

x
 tensor([[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]]])
torch.Size([2, 3, 5])
Result tensor([[[[ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.]]],


        [[[ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.]]]])


In [46]:
test = torch.zeros((5, 10), dtype=torch.float32)
rh = torch.tensor([1/i for i in range(1, 6)])
lh = torch.flip(rh, (0,))
print(lh)

test[0, :] = torch.concat([lh, rh])
print(test)

tensor([0.2000, 0.2500, 0.3333, 0.5000, 1.0000])
tensor([[0.2000, 0.2500, 0.3333, 0.5000, 1.0000, 1.0000, 0.5000, 0.3333, 0.2500,
         0.2000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])
