In [2]:
import scipy
import numpy as np
x = np.array([[[1.0,2.0,3.0,4.0,5.0]]*3]*2)
k = np.array([0.0,0,1.0,0,0])

print("x", x)

res2 = scipy.ndimage.convolve1d(x, k, axis=-1, mode='constant', cval=0.0) #convolution using scipy straight forward

print("res", res2)

x [[[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]

 [[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]]
res [[[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]

 [[1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]
  [1. 2. 3. 4. 5.]]]


In [3]:
import torch
import torch.nn as nn
#convolution using pytorch

x = torch.tensor([[[1.0,2,3,4,5]]*3]*2) #batch of 2 2d tensor
k = torch.tensor([[0,0,2.0,0,0]]*3, dtype=torch.float32) #2d kernel

print("x\n", x)
print("filter\n", k)

res = nn.functional.conv1d(x, k[:, None, :], groups=3, padding="same") #allowing theta dependance in filter

print(res)

c:\Users\salom\anaconda3\envs\KEX\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


x
 tensor([[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]]])
filter
 tensor([[0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 2., 0., 0.]])
tensor([[[ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.]],

        [[ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.],
         [ 2.,  4.,  6.,  8., 10.]]])


In [4]:
x = torch.tensor([
    [
        [1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5]
    ],
    [
        [1,2,3,4,5],
        [1,2,3,4,5],
        [1,2,3,4,5]
    ]

], dtype=torch.float32)
print("x\n",x)
print(x.shape)
# print(x[None].shape)
k = torch.tensor([0,0,2,0,0], dtype=torch.float32) #1d kernel

res = nn.functional.conv2d(x[:, None], k[None, None, None], padding="same") # no theta depandance in filter

print("Result", res)

x
 tensor([[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]]])
torch.Size([2, 3, 5])
Result tensor([[[[ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.]]],


        [[[ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.],
          [ 2.,  4.,  6.,  8., 10.]]]])


In [5]:
test = torch.zeros((5, 10), dtype=torch.float32)
rh = torch.tensor([1/i for i in range(1, 6)])
lh = torch.flip(rh, (0,))
print(lh)

test[0, :] = torch.concat([lh, rh])
print(test)

tensor([0.2000, 0.2500, 0.3333, 0.5000, 1.0000])
tensor([[0.2000, 0.2500, 0.3333, 0.5000, 1.0000, 1.0000, 0.5000, 0.3333, 0.2500,
         0.2000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])


In [14]:
x = torch.arange(6)

f = torch.fft.fft(x)
fr = torch.fft.rfft(x)
y = torch.fft.ifft(f)
yr = torch.fft.irfft(fr)
print(x.shape, x)
print(f.shape, f)
print(fr.shape, fr)
print(y.shape, y)
print(yr.shape, yr)


torch.Size([6]) tensor([0, 1, 2, 3, 4, 5])
torch.Size([6]) tensor([15.+0.0000j, -3.+5.1962j, -3.+1.7321j, -3.+0.0000j, -3.-1.7321j,
        -3.-5.1962j])
torch.Size([4]) tensor([15.+0.0000j, -3.+5.1962j, -3.+1.7321j, -3.+0.0000j])
torch.Size([6]) tensor([0.0000+0.j, 1.0000+0.j, 2.0000+0.j, 3.0000+0.j, 4.0000+0.j, 5.0000+0.j])
torch.Size([6]) tensor([0., 1., 2., 3., 4., 5.])


In [13]:
A = torch.tensor([
    [0.0, 1, -2, 3],
    [5, 6, 7, 8],
    [9 ,10, -11, 12]
])

print(torch.abs(A))
print(torch.mean(A))
print(torch.max(A, dim=-1, keepdim=True).values)
print(A / torch.max(A, dim=-1, keepdim=True).values)
print(A.view(-1).shape)
print(A.shape)

tensor([[ 0.,  1.,  2.,  3.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor(4.)
tensor([[ 3.],
        [ 8.],
        [12.]])
tensor([[ 0.0000,  0.3333, -0.6667,  1.0000],
        [ 0.6250,  0.7500,  0.8750,  1.0000],
        [ 0.7500,  0.8333, -0.9167,  1.0000]])
torch.Size([12])
torch.Size([3, 4])
